# Conda environment for the SCENIC+ pipeline.
# This is enhanced environment to add R, Seurat, and yaml functionality
#
# 2026/05/07
# Installation tested by Hee Woong Lim at CCHMC HPC; 
# But scenicplus run not tested yet
#

name: scenicplus_limlab
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11.8
  - pyyaml
  - pip
  - pybedtools
  # This specificiation is not mentioned in the official scenicplus page; manually added
  - setuptools<80
  # ---- R + other R-dependencies ----
  - r-base>=4.2
  - r-seurat
  - r-matrix
  - r-optparse
  # ---- Python deps best installed via pip ----
  - pip:
      - "scenicplus @ git+https://github.com/aertslab/scenicplus.git"
